spring:
  cloud:
    stream:
      bindings:
        posInvoice-input-channel:
          destination: pos-topic
        posInvoice-output-channel:
          destination: pos-mask-topic
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
