{
  "swagger": "2.0",
  "info": {
    "description": "Hello world spring-boot service",
    "title": "HELLO WORLD API"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "tags": [
    {
      "name": "hello-world-controller",
      "description": "Hello World Controller"
    }
  ],
  "paths": {
    "/v01/sayHello": {
      "get": {
        "tags": [
            "hello-world-controller"
        ],
        "summary": "helloWorld",
        "operationId": "helloWorldUsingGET",
        "produces": [
            "*/*"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Greetings"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "deprecated": false
      }
    }
  },
  "definitions": {
    "Greetings": {
      "type": "object",
      "properties": {
        "greetingBy": {
          "type": "string"
        },
        "greetingString": {
          "type": "string"
        }
      },
      "title": "Greetings"
    }
  }
}