INSERT INTO CUSTOMER(CUSTOMERID ,CUSTOMER_NAME ,CUSTOMER_TYPEID) values (1,'Alex',78);
INSERT INTO CUSTOMER(CUSTOMERID ,CUSTOMER_NAME ,CUSTOMER_TYPEID) values (2,'Jhon',78);
INSERT INTO CUSTOMER(CUSTOMERID ,CUSTOMER_NAME ,CUSTOMER_TYPEID) values (3,'Roberta',73);