INSERT INTO Items (ITEM_ID, DESCRIPTION, INVENTORY_STATUS,LAST_UPDATED_DATE) VALUES
   ('0001', 'Item number 1', 0,CURRENT_TIMESTAMP);
INSERT INTO Items (ITEM_ID, DESCRIPTION, INVENTORY_STATUS,LAST_UPDATED_DATE) VALUES
   ('0002', 'Item number 2', 0,CURRENT_TIMESTAMP);
INSERT INTO Items (ITEM_ID, DESCRIPTION, INVENTORY_STATUS,LAST_UPDATED_DATE) VALUES
   ('0003', 'Item number 3', 0,CURRENT_TIMESTAMP);
INSERT INTO Items (ITEM_ID, DESCRIPTION, INVENTORY_STATUS,LAST_UPDATED_DATE) VALUES
   ('0004', 'Item number 4', 0,CURRENT_TIMESTAMP);